apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: logs-api
  name: logs-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
